FROM lsstsqre/centos:7-stack-lsst_distrib-v29_2_1

WORKDIR /home/lsst/mnt

# The LSST environment is still activated per shell/script with:
# source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib
